version: "2"
services:
  main01:
    build: .
    volumes:
       - ./folder:/aplication/folder  
    environment:
       DOCKER_NAME: FILE01  
  main02:
    build: .
    volumes:
       - ./folder:/aplication/folder  
    environment:
       DOCKER_NAME: FILE02  
  main03:
    build: .
    volumes:
       - ./folder:/aplication/folder  
    environment:
       DOCKER_NAME: FILE03  


